export { default as CashSection } from "./CashSection";
export { default as EmployeeSection } from "./EmployeeSection";
export { default as DishSection } from "./EmployeeSection";
export { default as EstablishmentSection } from "./EstablishmentSection";
export { default as CategorySection } from "./CategorySection";
export { default as PaymentMethodSection } from "./PaymentMethodSection";
export { default as SalesReportSection } from "./SalesReportSection";
export { default as TableSection } from "./TableSection";
export { default as ReceiptReportSection } from "./ReceiptReportSection";
